### ISSUE TITLE
루틴 모달 오류 해결

### ISSUE THREAD

**Issue by staccato20** [Fitness-Mate/Frontend#240]
## 어떤 버그인가요?

루틴 모달에서
TypeError: Cannot read properties of undefined (reading 'data')
오류 발생

## 어떤 상황에서 발생한 버그인가요?

타 브랜치에서 main 브랜치로의 pr merge과정에서 스토리북 build 실패

## 예상 결과

컴포넌트에서 data를 읽기 전에 존재여부를 판단하도록 하거나 초기값을 설정하여 undifined 방지하도록 수정하여 스토리북 build 성공

**Comment by Whoknow77** [comment]
주석은 지우시고 작성해주세요!
